### ISSUE TITLE
Summarise cluster composition using dplyr

### ISSUE THREAD

**Issue by jamesboot** [tumorscholar/MASLD_scMultiome#7]
Hi Raju,

As discussed if you want to plot a summary of sample distribution across clusters or something similar you will need to use dplyr. See the code and explanation below.

#### Create summary data frame
```
summary <- post_meta %>%
    group_by(FlowSOM_metacluster) %>%
    count(Sample) %>%
    mutate(proportion = n / sum(n))
```

#### Explanation
- `%>%` is a special symbol in dplyr - it passes an object to a new function. In the above snipped the post_meta data frame (which should be your Seurat meta data) is passed to the `group_by()` function, the output of which is then passed to the `count()` function.
- `group_by()` groups your data by values in a defined column e.g. cluster - you need to define the name of the column inside `group_by()` - do not use quotes.
- `count()` - counts the occurrences of each of the variables in a given column e.g. the number of times each sample occurs - when put after `group_by()` it will count the occurrences of the variables in each group e.g. cluster.
- `mutate()` - creates a new column - in this case a new column called proportion which is the proportion of each sample in each `group_by()` variable.

#### Plot summary bar chart
```
  ggplot(summary, aes(x = Cluster, y = n, fill = Sample)) +
    geom_bar(stat = "identity", position = 'stack') +
    guides(fill = guide_legend(title = "Sample")) +
    theme(axis.text.x = element_text(
      angle = 90,
      vjust = 0.5,
      hjust = 1
    ))
```

#### Explanation
- Plot the `summary` dataframe created above.
- `y` should be the `n` column created in the dplyr code. Fill should be Sample or whatever attribute you have counted the occurrences of.
- `stat` must be `"identity"` and `position` must be `"stack"`
- Extra: if you want a percentage bar chart where everything is scaled to 1 (100%) rather than raw numbers you could use the `proportion` column created in the dplyr code.

**Comment by tumorscholar** [comment]
![Capture](https://github.com/tumorscholar/MASLD_scMultiome/assets/156453454/ac1009cd-ae27-4a93-81db-e892cc61ce80)
Hello James,
I managed to generate the plot as explained, but I am not able to scale the axis to 100%


**Create tissue summary data frame and plot summary chart**
```summary <- SeuObj@meta.data %>%
 group_by(Tissue) %>%
 count(seurat_clusters) %>%
 mutate(proportion = n / sum(n))

ggplot(summary, aes(x = seurat_clusters, y = proportion, fill = Tissue)) +
 geom_bar(stat = "identity", position = 'stack') +
 guides(fill = guide_legend(title = "Tissue")) +
 theme(axis.text.x = element_text(
  angle = 90,
  vjust = 0.5,
  hjust = 1
 ))

![image](https://github.com/tumorscholar/MASLD_scMultiome/assets/156453454/db2f5209-1e43-4867-b5da-efc26660ac73)

**Comment by jamesboot** [comment]
For proportional bar chart you need to change the ggplot code to something like:

```
# Plot summary proportional bar chart
ggplot(summary, aes(x = Cluster, y = proportion, fill = stage)) +
  geom_bar(stat = "identity") +
  guides(fill=guide_legend(title="Treatment")) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```
